/* 200 levels: [answer, clue]. Answers are A-Z only, 3 to 11 letters, all unique.
   Each tier is 20 levels. Add more by appending to WORDS and a name to TIERS. */
var WORDS=[
/* 1-20 Sharp */
['ECHO','I answer without a mouth and repeat without a brain.'],
['SHADOW','I am always behind you in sunshine and gone in the dark.'],
['TIME','Everyone spends me, nobody can save me, and I never stop moving.'],
['HOLE','The more you take away from me, the bigger I become.'],
['EGG','No lid, no door, yet a golden treasure hides inside me.'],
['COMB','I have teeth but I never bite.'],
['MAP','I have cities with no houses, rivers with no water and roads with no cars.'],
['STAMP','I stick to one thing but travel all around the world.'],
['PENCIL','I get shorter as I work, and I carry my own rubber at my tail.'],
['SPONGE','I am full of holes, yet I hold water.'],
['TOWEL','I get wetter the more I dry.'],
['CLOUD','I fly without wings and cry without eyes.'],
['BREATH','Take me in, let me out, hold me too long and you turn blue.'],
['NAME','Other people use me more than you do, yet I belong to you.'],
['SILENCE','Say my name and I am gone.'],
['MIRROR','I show you everything, say not a word, and bring bad luck when broken.'],
['COAL','I was a forest once. Now I am a black rock that burns.'],
['FUTURE','I have not happened yet, and everything you do today shapes me.'],
['PROMISE','Easy to make, hard to keep, and broken by a single lie.'],
['FOOTPRINT','I am left behind with every step on wet sand.'],
/* 21-40 Tricky */
['PIANO','I have eighty-eight keys and no doors, and hammers strike my strings.'],
['KEYBOARD','I have keys but open no locks, and space but no room.'],
['RIVER','I have a mouth and a bed, yet I never eat or sleep.'],
['BOOK','I have a spine and leaves, but I am neither a body nor a plant.'],
['CLOCK','My hands never touch anything, yet I always point to the hour.'],
['BANK','I have branches but no leaves, and a vault but no wine.'],
['CAMERA','I freeze a moment without any ice, and I have a lens but I am not glasses.'],
['NEEDLE','I have an eye but cannot see, and I lead thread through cloth.'],
['ENVELOPE','Sealed with a lick, I carry words, and I am thrown away once opened.'],
['ICEBERG','Most of me hides below the surface, and I once sank a famous ship.'],
['SOAP','The more I am used, the less I become, yet I leave things cleaner.'],
['BOTTLE','I have a neck but no head, and sometimes I carry messages across the sea.'],
['STAIRS','We go up and down without ever moving.'],
['FIRE','Feed me and I grow. Give me water and I die.'],
['CHESS','Kings and queens fight on my squares, yet no blood is spilled.'],
['WINDOW','I keep the rain out but let the light in, and sometimes you open me for a breeze.'],
['TOOTH','I can be filled, crowned, capped and pulled out.'],
['ANCHOR','I hold a ship in place by diving to the bottom.'],
['GLOVE','I have five fingers but no bones, and no life of my own.'],
['MEMORY','I hold your past, fade with age, and vanish at the worst moment.'],
/* 41-60 Brutal */
['PARADOX','I am a truth that sounds like a lie, like the barber who shaves everyone who does not shave himself.'],
['HORIZON','I retreat as you approach, and the sea meets the sky at my line.'],
['SECRET','Tell me and I am no longer what I was.'],
['OXYGEN','You breathe me, fire needs me, and my symbol is the letter O.'],
['PYRAMID','Four triangles meet at my peak, and I was built to house a pharaoh.'],
['ECLIPSE','When the moon hides the sun, or Earth hides the moon, I appear.'],
['LABYRINTH','A Minotaur lived in my winding passages.'],
['SUNDIAL','I tell the time with nothing but a shadow.'],
['AVALANCHE','A mountain\'s snow breaks loose and thunders down: that is me.'],
['HORSESHOE','Nailed to a hoof, or hung over a door for luck.'],
['HOURGLASS','Sand falls through my narrow waist to count the time.'],
['COMPASS','I always point north, yet I never travel.'],
['LIGHTHOUSE','I stand on the coast and warn ships with a rotating beam.'],
['SILHOUETTE','I am a dark outline against the light, with no detail inside.'],
['DEADLINE','You do not want to cross me, yet you rush towards me.'],
['INFLATION','Prices rise and your money buys less because of me.'],
['TELEPHONE','Bell patented me, and I carry your voice along wires.'],
['EQUATOR','An imaginary belt around the middle of the Earth.'],
['VACUUM','Empty space with no air, or the machine that sucks up dust.'],
['OXYMORON','Jumbo shrimp and deafening silence are examples of me.'],
/* 61-80 Cruel */
['NOMAD','I have no fixed home and wander with my tent.'],
['ALCHEMY','The medieval dream of turning lead into gold.'],
['CHAMELEON','A lizard that changes colour to match its surroundings.'],
['METAPHOR','“Life is a journey” is one of these: a figure of speech that says one thing is another.'],
['PENDULUM','I swing back and forth inside a grandfather clock.'],
['TSUNAMI','A giant wave born from an earthquake under the sea.'],
['MIRAGE','Desert travellers see water in me, but I am only an illusion made of light.'],
['QUICKSAND','The harder you struggle in me, the deeper you sink.'],
['BOOMERANG','A thrown weapon that returns to the thrower.'],
['SYMPHONY','An orchestra\'s long work, played in several movements.'],
['DIAGNOSIS','A doctor\'s conclusion about what is wrong with you.'],
['PARACHUTE','I open above your head so that you fall slowly.'],
['EXILE','Banished from your homeland.'],
['MONSOON','A seasonal wind that brings the heavy rains to South Asia.'],
['CATALYST','I speed up a reaction without being used up myself.'],
['ASTEROID','A rocky body that orbits the sun, many between Mars and Jupiter.'],
['SOLSTICE','The longest or the shortest day of the year.'],
['BLUEPRINT','The architect\'s plan, drawn before a building rises.'],
['FRONTIER','The edge of the known world, where settled land ends.'],
['ENIGMA','A puzzle wrapped in mystery. A famous WWII cipher machine shared my name.'],
/* 81-100 Impossible */
['PALINDROME','Level, radar and kayak all share my property of reading the same both ways.'],
['ANAGRAM','Rearrange the letters of “listen” and you get “silent”: that trick is me.'],
['ACRONYM','NASA and laser are built from initials, and I am the word for that.'],
['SYNONYM','Big and large are a pair of these.'],
['EUPHORIA','An overwhelming feeling of intense happiness.'],
['NOSTALGIA','A bittersweet longing for the past.'],
['SERENDIPITY','A happy accident: finding something wonderful when you were not looking for it.'],
['QUARANTINE','My name comes from forty days, and I keep the sick away from the healthy.'],
['CAMOUFLAGE','Blending into the background to hide from predators.'],
['LIGHTNING','I strike first, and the thunder only follows after the flash.'],
['HYPOTHESIS','A scientist\'s educated guess, waiting to be tested.'],
['PHILOSOPHY','The love of wisdom, practised by Socrates in the marketplace.'],
['CATASTROPHE','A sudden disaster, or the tragic end of a Greek play.'],
['EPHEMERAL','Lasting only a very short time, like the life of a mayfly.'],
['MELANCHOLY','A deep, lingering sadness with no clear cause.'],
['RENAISSANCE','The rebirth of art and learning in Europe after the Middle Ages.'],
['ECOSYSTEM','A community of living things together with the environment they share.'],
['ENCRYPTION','Scrambling data so that only the holder of the key can read it.'],
['INFINITY','A number bigger than any number, written as a sideways eight.'],
['OMNISCIENT','Knowing everything, like a narrator who sees every character\'s thoughts.'],
/* 101-120 Mythic */
['UMBRELLA','I have ribs but no bones, and I open whenever it rains.'],
['ZIPPER','My teeth lock together without a single bite, and I close your jacket.'],
['LADDER','I have rungs but no voice, and I lean on walls to lift you higher.'],
['COIN','Heads or tails, flip me to settle an argument.'],
['CANDLE','I am tall when I am young and short when I am old.'],
['BALLOON','I am full of air but not alive, and one prick ends me.'],
['THIMBLE','A tiny metal cap that protects a fingertip from the needle.'],
['TUNNEL','I go through the mountain instead of over it.'],
['BRIDGE','I join two banks without moving, and I carry you across the water.'],
['SCISSORS','Two blades joined in the middle: I cut without a single bite.'],
['MAGNET','I pull iron without hands, and I always have two poles.'],
['PRISM','White light goes into me and a rainbow comes out.'],
['FOSSIL','A stone that remembers a creature from millions of years ago.'],
['CRATER','A bowl left in the ground by a falling meteor.'],
['GLACIER','A slow river of ice that moves only a few inches a day.'],
['TORNADO','A spinning funnel of wind that touches the ground.'],
['DESERT','I get less than ten inches of rain a year, and camels love me.'],
['OASIS','A green island of water in a sea of sand.'],
['RAINBOW','I appear when sun meets rain. I have seven colours but no end.'],
['WHIRLPOOL','A swirling hole in the water that pulls things down.'],
/* 121-140 Legendary */
['GRAVITY','What goes up must come down because of me.'],
['TRUTH','Often hard to hear, yet the best cure for a lie.'],
['COURAGE','Fear is my partner, because I mean acting in spite of it.'],
['PATIENCE','A virtue that waits without complaint.'],
['GENIUS','Edison said I am one percent inspiration and ninety-nine percent perspiration.'],
['WISDOM','Knowing a tomato is a fruit is knowledge. Not putting it in a fruit salad is me.'],
['REFLECTION','Still lakes and mirrors give me, and so does deep thought.'],
['DISTANCE','The space between two places, measured in miles or kilometres.'],
['HARMONY','Notes that sound good together, or peace between people.'],
['DESTINY','Fate by another name: what is meant to happen.'],
['ILLUSION','A magician\'s trick, a thing that is not what it seems.'],
['VICTORY','Won after the battle, and the V sign stands for me.'],
['SURRENDER','To give up the fight and raise a white flag.'],
['LOYALTY','A dog is famous for me, staying faithful no matter what.'],
['AMBITION','A strong desire to achieve, driving the climb to the top.'],
['ELOQUENCE','Fluent, persuasive speech, like a great orator\'s gift.'],
['SOLITUDE','Being alone without being lonely.'],
['CURIOSITY','It killed the cat, they say, but it also made scientists.'],
['INTUITION','A gut feeling that knows without reasoning.'],
['BETRAYAL','Brutus did it to Caesar: breaking someone\'s trust.'],
/* 141-160 Cosmic */
['GALAXY','Billions of stars held together by gravity. Ours is the Milky Way.'],
['COMET','An icy visitor with a glowing tail, like Halley\'s.'],
['NEBULA','A vast cloud of gas and dust where stars are born.'],
['PULSAR','A spinning neutron star that blinks like a lighthouse in space.'],
['SUPERNOVA','The explosive death of a massive star.'],
['SINGULARITY','The point at the centre of a black hole where known physics breaks down.'],
['ORBIT','The curved path a planet takes around its star.'],
['SATELLITE','A body that circles a planet. The moon is a natural one.'],
['TELESCOPE','Galileo pointed one at the sky to find Jupiter\'s moons.'],
['UNIVERSE','Every star, planet and galaxy together make this.'],
['PHOTON','A particle of light with no mass.'],
['NEUTRON','I sit in the nucleus and carry no charge.'],
['MOLECULE','Two hydrogens and one oxygen make water. That unit is me.'],
['CHLOROPHYLL','The green pigment that lets leaves make food from sunlight.'],
['EVOLUTION','Darwin\'s theory of how species change over generations.'],
['DNA','A double helix that carries the code of life.'],
['ELECTRON','A tiny negative charge that orbits the atom\'s core.'],
['MAGNETISM','Compasses and fridge doors both feel this force.'],
['SONAR','Submarines find objects underwater by listening to sound pulses that bounce back.'],
['SPECTRUM','All the colours of the rainbow, in order.'],
/* 161-180 Eternal */
['ALPHABET','From A to Z, I am the full set of letters.'],
['LIBRARIAN','The keeper of the books who always says shh.'],
['ASTRONAUT','A space traveller in a pressurised suit.'],
['ARCHIPELAGO','A chain of islands, like the Andamans.'],
['PENINSULA','Land surrounded by water on three sides. South India is one.'],
['HEMISPHERE','Half a globe: north or south, east or west.'],
['LONGITUDE','Imaginary lines running from pole to pole.'],
['BAROMETER','It measures air pressure to predict the weather.'],
['THERMOMETER','It tells you how hot or how cold you are.'],
['STETHOSCOPE','A doctor listens to your heartbeat with me.'],
['MICROSCOPE','Make the tiny look huge and see the cells with me.'],
['ARCHITECT','The one who designs buildings before they are built.'],
['DEMOCRACY','Government by the people, for the people.'],
['PARLIAMENT','Where lawmakers debate. In India, mine sits in New Delhi.'],
['AMBASSADOR','A country\'s top diplomat posted abroad.'],
['TREASURE','X marks the spot where pirates buried me.'],
['ARCHAEOLOGY','The study of the past by digging up ruins and artefacts.'],
['VOCABULARY','All the words you know.'],
['BIOGRAPHY','A book that tells the story of someone\'s life, written by another person.'],
['LEGEND','A famous old story, or a person admired for greatness.'],
/* 181-200 Final */
['FINGERPRINT','No two are alike, even in twins, and detectives dust for me.'],
['RIDDLE','I ask a question that hides its own answer, and you are solving me right now.'],
['STOPWATCH','I count every second you race against me, just like this game.'],
['ADRENALINE','The hormone that makes your heart race when you panic.'],
['INNOVATION','A new idea turned into something useful.'],
['PERSISTENCE','Keep going despite failure: the quality behind every record.'],
['DISCIPLINE','Doing what must be done even when you do not feel like it.'],
['DIFFERENCE','What separates two things that are not the same.'],
['WHISPER','Speak softly, with barely any sound, for one ear only.'],
['THUNDERBOLT','Lightning and its thunder together, a sudden shock.'],
['UNDERGROUND','Metro lines run here, beneath the city streets.'],
['HURRICANE','A storm that spins around a calm eye over warm oceans.'],
['CROCODILE','I cry fake tears and lurk in rivers with a toothy grin.'],
['PORCUPINE','My quills are my armour, and I am a rodent you should not hug.'],
['KANGAROO','I carry my baby in a pouch and bounce across Australia.'],
['NIGHTINGALE','A songbird that sings in the dark, and the surname of a famous nurse.'],
['FIREWORKS','Colourful booms that light up the sky on Diwali night.'],
['CELEBRATION','A party marking a special occasion with joy.'],
['CHALLENGE','Something difficult that tests your skill, like this game.'],
['CHAMPION','Wins the final and takes home the trophy.']
];
var TIERS=[['Sharp',1],['Tricky',21],['Brutal',41],['Cruel',61],['Impossible',81],['Mythic',101],['Legendary',121],['Cosmic',141],['Eternal',161],['Final',181]];
var TOTAL=WORDS.length;
